# Database Configuration
# Copy this file to config.yml and update the values

db:
  # PostgreSQL connection string
  # Format: postgresql://username:password@host:port/database_name
  url: "postgresql://your_username:your_password@localhost:5432/your_database"

# Application Settings
app:
  port: 3000
  env: development
  secret: your-secret-key-here  # Change this to a secure random string in production

# Session Configuration
session:
  secret: your-session-secret  # Change this to a secure random string in production
  cookieMaxAge: 86400000  # 24 hours in milliseconds

# Security Headers
security:
  contentSecurityPolicy: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:;"
  hsts: true
  xssProtection: true
  nosniff: true
  xFrameOptions: "DENY"

# Logging
logging:
  level: "info"  # error, warn, info, debug, trace
  file: "logs/app.log"
  console: true

# CORS Configuration
cors:
  enabled: true
  origin: 
    - "http://localhost:3000"
    - "https://your-production-domain.com"
  methods: ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"]
  allowedHeaders: ["Content-Type", "Authorization"]
  credentials: true

# Rate Limiting
rateLimit:
  windowMs: 15 * 60 * 1000,  # 15 minutes
  max: 100  # limit each IP to 100 requests per windowMs

# API Configuration
api:
  prefix: "/api"
  version: "v1"
  docs: "/api-docs"  # Set to false to disable

# Email Configuration (if needed)
# email:
#   host: "smtp.example.com"
#   port: 587
#   secure: false  # true for 465, false for other ports
#   auth:
#     user: "your-email@example.com"
#     pass: "your-email-password"
#   from: "Your App <noreply@example.com>"

# Feature Flags
features:
  maintenance: false
  registration: true
  emailVerification: false

# External Services
externalServices:
  # Add any external service configurations here
  # Example:
  # googleMaps:
  #   apiKey: "your-google-maps-api-key"
